[build]
base = "apps/my-hfn-world"
command = "npm run build"
publish = "apps/my-hfn-world/build/client"
edge_functions = ".netlify/edge-functions"

[dev]
base = "./apps/my-hfn-world"
command = "npm run _dev"
framework = "vite"

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/build/*"

[headers.values]

"Cache-Control" = "public, max-age=31560000, immutable"

[functions]
directory=".netlify/edge-functions"

