import daisyuiPlugin from "daisyui";

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["../../pages/mhw-pages/dist/**/*.{js,jsx,ts,tsx}"],
  daisyui: {
    darkTheme: true,
    themes: [
      // "pastel",
      "light",
      // "dark",
      // "cupcake",
      // "bumblebee",
      // "emerald",
      // "corporate",
      // "synthwave",
      // "retro",
      // "cyberpunk",
      // "valentine",
      // "halloween",
      // "garden",
      // "forest",
      // "aqua",
      // "lofi",
      // "pastel",
      // "fantasy",
      // "wireframe",
      // "black",
      // "luxury",
      // "dracula",
      // "cmyk",
      // "autumn",
      // "business",
      // "acid",
      // "lemonade",
      // "night",
      // "coffee",
      // "winter",
      // "dim",
      // "nord",
      // "sunset",
    ],
  },
  plugins: [daisyuiPlugin],
};
